name: Build LaTeX document
on: [push]
jobs:
  Build_LaTeX_Resume:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile Resume
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf
